"""initial schema

Revision ID: ceaec9fbadcf
Revises: 
Create Date: 2026-08-31 17:11:44.349323
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = 'ceaec9fbadcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.String(length=48), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.Column('mime', sa.String(length=96), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_run_id'), ['run_id'], unique=False)

    op.create_table('audit',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event'), ['event'], unique=False)

    op.create_table('collections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('source_roots', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('acl', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('embedding_model', sa.String(length=96), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('suite', sa.String(length=64), nullable=False),
    sa.Column('profile', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_runs_suite'), ['suite'], unique=False)

    op.create_table('ingest_errors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('collection_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_errors_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_errors_document_id'), ['document_id'], unique=False)

    op.create_table('ingest_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('collection_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_ingest_jobs_claim', ['status', 'priority', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_jobs_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_jobs_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_jobs_status'), ['status'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=48), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('facts_established', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('done', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('remaining', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('blockers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stuck', sa.Boolean(), nullable=False),
    sa.Column('next_action_hint', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_task_id'), ['task_id'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('embedding_ref', sa.String(length=64), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(length=96), nullable=False),
    sa.Column('family', sa.String(length=48), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(length=24), nullable=False),
    sa.Column('params_b', sa.Float(), nullable=False),
    sa.Column('license', sa.String(length=48), nullable=True),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('context_len', sa.Integer(), nullable=False),
    sa.Column('serve_context_len', sa.Integer(), nullable=False),
    sa.Column('vram_gb', sa.Float(), nullable=False),
    sa.Column('quant', sa.String(length=24), nullable=True),
    sa.Column('roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('serve_args', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('probes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.String(length=48), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('args_summary', sa.Text(), nullable=True),
    sa.Column('rule', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_log_run_id'), ['run_id'], unique=False)

    op.create_table('probe_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=96), nullable=False),
    sa.Column('probe', sa.String(length=48), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('probe_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_probe_results_model_id'), ['model_id'], unique=False)

    op.create_table('router_decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.String(length=48), nullable=True),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('chosen', sa.String(length=96), nullable=False),
    sa.Column('rejected', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('router_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_router_decisions_run_id'), ['run_id'], unique=False)

    op.create_table('seal_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('process', sa.String(length=96), nullable=False),
    sa.Column('dest', sa.String(length=256), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('stack', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('workspace_path', sa.Text(), nullable=False),
    sa.Column('collections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parent_session_id', sa.String(length=32), nullable=True),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('triggers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tools', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spans',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('start_ns', sa.Integer(), nullable=False),
    sa.Column('end_ns', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.String(length=48), nullable=True),
    sa.Column('step_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spans_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index('ix_spans_trace_kind', ['trace_id', 'kind'], unique=False)

    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('step_id', sa.String(length=32), nullable=True),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=48), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('args', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('permission', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result_artifact_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sandbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'idempotency_key', name='uq_toolcall_idem')
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_calls_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_calls_step_id'), ['step_id'], unique=False)

    op.create_table('verifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=48), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reviewer', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('escalation_applied', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_task_id'), ['task_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('collection_id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.String(length=48), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('revision', sa.String(length=32), nullable=True),
    sa.Column('doc_number', sa.String(length=128), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'path', name='uq_document_path')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_doc_number'), ['doc_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('eval_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('eval_run_id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=96), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_results_eval_run_id'), ['eval_run_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('goal_text', sa.Text(), nullable=False),
    sa.Column('goal_spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('budgets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('budget_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('workspace_path', sa.Text(), nullable=False),
    sa.Column('collections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('collection_id', sa.String(length=32), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('context_prefix', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('parent_chunk_id', sa.String(length=32), nullable=True),
    sa.Column('tombstoned', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index('ix_chunks_doc_page', ['document_id', 'page_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_parent_chunk_id'), ['parent_chunk_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('group_key', sa.String(length=160), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.String(length=32), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_versions_group_key'), ['group_key'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('has_text_layer', sa.Boolean(), nullable=False),
    sa.Column('text_quality', sa.Float(), nullable=False),
    sa.Column('image_artifact_id', sa.String(length=32), nullable=True),
    sa.Column('thumb_artifact_id', sa.String(length=32), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_no', name='uq_page')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_document_id'), ['document_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('acceptance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('budget', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_hint', sa.String(length=96), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('ladder_rung', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('parent_task_id', sa.String(length=48), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=48), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('thought', sa.Text(), nullable=True),
    sa.Column('action', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('observation_artifact_id', sa.String(length=32), nullable=True),
    sa.Column('tokens', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('model_id', sa.String(length=96), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_steps_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_steps_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steps_task_id'))
        batch_op.drop_index(batch_op.f('ix_steps_run_id'))

    op.drop_table('steps')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_run_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_document_id'))

    op.drop_table('pages')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_group_key'))
        batch_op.drop_index(batch_op.f('ix_document_versions_document_id'))

    op.drop_table('document_versions')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_parent_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_document_id'))
        batch_op.drop_index('ix_chunks_doc_page')
        batch_op.drop_index(batch_op.f('ix_chunks_collection_id'))

    op.drop_table('chunks')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_session_id'))

    op.drop_table('runs')
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_results_eval_run_id'))

    op.drop_table('eval_results')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_doc_type'))
        batch_op.drop_index(batch_op.f('ix_documents_doc_number'))
        batch_op.drop_index(batch_op.f('ix_documents_collection_id'))

    op.drop_table('documents')
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_task_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_run_id'))

    op.drop_table('verifications')
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_calls_step_id'))
        batch_op.drop_index(batch_op.f('ix_tool_calls_run_id'))

    op.drop_table('tool_calls')
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.drop_index('ix_spans_trace_kind')
        batch_op.drop_index(batch_op.f('ix_spans_trace_id'))
        batch_op.drop_index(batch_op.f('ix_spans_run_id'))
        batch_op.drop_index(batch_op.f('ix_spans_name'))
        batch_op.drop_index(batch_op.f('ix_spans_kind'))

    op.drop_table('spans')
    op.drop_table('skills')
    op.drop_table('sessions')
    op.drop_table('seal_events')
    with op.batch_alter_table('router_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_router_decisions_run_id'))

    op.drop_table('router_decisions')
    with op.batch_alter_table('probe_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_probe_results_model_id'))

    op.drop_table('probe_results')
    with op.batch_alter_table('permissions_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_log_run_id'))

    op.drop_table('permissions_log')
    op.drop_table('models')
    op.drop_table('memories')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_task_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_run_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_stage'))
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_document_id'))
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_collection_id'))
        batch_op.drop_index('ix_ingest_jobs_claim')

    op.drop_table('ingest_jobs')
    with op.batch_alter_table('ingest_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_errors_document_id'))
        batch_op.drop_index(batch_op.f('ix_ingest_errors_collection_id'))

    op.drop_table('ingest_errors')
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_runs_suite'))

    op.drop_table('eval_runs')
    op.drop_table('collections')
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event'))

    op.drop_table('audit')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_run_id'))

    op.drop_table('artifacts')
    # ### end Alembic commands ###
