"""Generate TypeScript protocol types (tui/src/rpc/generated.ts) and docs/PROTOCOL.md.

Run via `pnpm run gen:types` (which calls `uv run python scripts/gen_types.py`).
Both outputs are committed so offline builds never need to regenerate.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))

from yantra_server.protocol.export import protocol_schemas  # noqa: E402


def ts_type(schema: dict[str, Any] | bool, defs: dict[str, Any]) -> str:
    if schema is True or schema == {}:
        return "unknown"
    if schema is False:
        return "never"
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(sorted({ts_type(s, defs) for s in schema["anyOf"]}))
    if "allOf" in schema and len(schema["allOf"]) == 1:
        return ts_type(schema["allOf"][0], defs)
    stype = schema.get("type")
    if isinstance(stype, list):
        return " | ".join(sorted({ts_type({**schema, "type": t}, defs) for t in stype}))
    if stype == "array":
        if "prefixItems" in schema:
            inner = ", ".join(ts_type(s, defs) for s in schema["prefixItems"])
            return f"[{inner}]"
        item = ts_type(schema.get("items", {}), defs)
        return f"Array<{item}>" if "|" in item else f"{item}[]"
    if stype == "object" or "properties" in schema:
        props = schema.get("properties")
        if not props:
            extra = schema.get("additionalProperties", True)
            value = ts_type(extra, defs) if isinstance(extra, dict) else "unknown"
            return f"Record<string, {value}>"
        required = set(schema.get("required", []))
        fields = []
        for name, sub in props.items():
            optional = "" if name in required else "?"
            fields.append(f"  {name}{optional}: {ts_type(sub, defs)};")
        return "{\n" + "\n".join(fields) + "\n}"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(str(stype), "unknown")


def emit_ts(schemas: dict[str, Any]) -> str:
    defs: dict[str, Any] = schemas["$defs"]
    lines = [
        "// GENERATED by scripts/gen_types.py — do not edit by hand.",
        "/* eslint-disable */",
        "",
    ]
    for name in sorted(defs):
        body = ts_type(defs[name], defs)
        if body.startswith("{"):
            lines.append(f"export interface {name} {body}\n")
        else:
            lines.append(f"export type {name} = {body};\n")

    def ref_name(entry: dict[str, Any]) -> str:
        return str(entry["$ref"]).rsplit("/", 1)[-1]

    req_params = ", ".join(
        f"'{m}': {ref_name(e['params'])}" for m, e in sorted(schemas["requests"].items())
    )
    req_results = ", ".join(
        f"'{m}': {ref_name(e['result'])}"
        for m, e in sorted(schemas["requests"].items())
        if "result" in e
    )
    notes = ", ".join(f"'{m}': {ref_name(e)}" for m, e in sorted(schemas["notifications"].items()))
    lines.append(f"export interface RequestParamsMap {{ {req_params} }}\n")
    lines.append(f"export interface RequestResultMap {{ {req_results} }}\n")
    lines.append(f"export interface NotificationMap {{ {notes} }}\n")
    lines.append("export type RpcMethod = keyof RequestParamsMap;\n")
    lines.append("export type NotificationMethod = keyof NotificationMap;\n")
    return "\n".join(lines)


def emit_docs(schemas: dict[str, Any]) -> str:
    lines = [
        "# YANTRA RPC protocol",
        "",
        "JSON-RPC 2.0 over WebSocket at `ws://127.0.0.1:7331/rpc`. Requests carry `id`,",
        "`method`, `params`; notifications (server→client) carry `method`, `params` with a",
        "per-run monotonic `seq` for reconnect replay (`session.resume {last_seq}`).",
        "",
        "This file is generated by `scripts/gen_types.py` from",
        "`server/yantra_server/protocol/messages.py` — regenerate with `pnpm run gen:types`.",
        "",
        "## Requests",
        "",
    ]
    for method, entry in sorted(schemas["requests"].items()):
        lines.append(f"### `{method}`")
        lines.append("")
        lines.append("Params schema:")
        lines.append("```json")
        lines.append(json.dumps(_resolve(entry["params"], schemas["$defs"]), indent=2))
        lines.append("```")
        if "result" in entry:
            lines.append("Result schema:")
            lines.append("```json")
            lines.append(json.dumps(_resolve(entry["result"], schemas["$defs"]), indent=2))
            lines.append("```")
        lines.append("")
    lines.append("## Notifications (server → client)")
    lines.append("")
    for method, entry in sorted(schemas["notifications"].items()):
        lines.append(f"### `{method}`")
        lines.append("```json")
        lines.append(json.dumps(_resolve(entry, schemas["$defs"]), indent=2))
        lines.append("```")
        lines.append("")
    return "\n".join(lines)


def _resolve(entry: dict[str, Any], defs: dict[str, Any]) -> dict[str, Any]:
    if "$ref" in entry:
        return dict(defs[str(entry["$ref"]).rsplit("/", 1)[-1]])
    return entry


def main() -> None:
    schemas = protocol_schemas()
    ts_out = ROOT / "tui" / "src" / "rpc" / "generated.ts"
    ts_out.parent.mkdir(parents=True, exist_ok=True)
    ts_out.write_text(emit_ts(schemas), encoding="utf-8", newline="\n")
    docs_out = ROOT / "docs" / "PROTOCOL.md"
    docs_out.write_text(emit_docs(schemas), encoding="utf-8", newline="\n")
    print(f"wrote {ts_out.relative_to(ROOT)} and {docs_out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
